# Generated by Django 5.0.6 on 2024-06-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filepath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3filepath', models.CharField(max_length=100)),
                ('datakeyname', models.CharField(max_length=100)),
                ('filestatus', models.CharField(max_length=100)),
            ],
        ),
    ]
